name: Flutter CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'temurin' # Use 'temurin' for a supported distribution
        java-version: '11' # Use the LTS version of Java
    #... rest of your steps

    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.16.5' # Use the correct Flutter version
    - name: Get Flutter Dependencies
      run: flutter pub get
    - name: Build Flutter Web App
      run: flutter build web
    - name: Deploy to Firebase
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: "${{ secrets.GITHUB_TOKEN }}"
        firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLUTTER_WEB }}"
        channelId: live # Use 'live' to deploy to the live channel
      env:
        FIREBASE_CLI_PREVIEWS: true
